package com.example.scheduleme.Service.Dao;

import androidx.lifecycle.MutableLiveData;

import com.example.scheduleme.Service.Model.Task;

import java.util.List;

public interface TaskDao {
      List<Task> getTasks(String selectTable);
     long insert_data(String selectTable,String title,String description, String dueDate);
     boolean updateDatabase(String selectTable, long _id, String title, String description, String dueDate,int corrTabID,String corrTabName, boolean navigation_clicked);
     boolean deleteData(long id, String title, String description, String dueDate,int corrTabID,String corrTabName, boolean navigation_clicked);
     int getLastAutoGeneratedKey(String tableName);
     void doneTaskDelete(long id);
}
